{
 "title": "Tesla Track Dashboard - Model 3 Performance",
 "time": { "from": "2024-01-01T18:00:34.000Z", "to": "2024-01-01T18:02:20.154Z" },
 "templating": {
  "list": [
   {
    "name": "Event",
    "label": "Event",
    "query": "SELECT table_name\nFROM information_schema.tables\nWHERE table_type = 'BASE TABLE'\nAND table_schema NOT IN ('pg_catalog', 'information_schema');"
   },
   {
    "name": "Session",
    "label": "Session",
    "query": "SELECT DISTINCT session from $Event;"
   },
   {
    "name": "Lap",
    "label": "Lap",
    "query": "SELECT DISTINCT lap FROM $Event WHERE session = $Session;"
   }
  ]
 },
 "panels": [
  { "title": "Session Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fastest Lap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  lap AS \"Lap\"\nFROM \n  $Event \nWHERE \n  session = $Session \nGROUP BY \n  lap \nORDER BY \n  MAX(elapsed_time)\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Top Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  MAX(speed) AS top_speed \nFROM\n  $Event \nWHERE \n  session = $Session;"
    }
   ]
  },
  {
   "title": "Max Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  MAX(power_level) AS max_power_level \nFROM \n  $Event\nWHERE\n  session = $Session;"
    }
   ]
  },
  {
   "title": "Max Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    sub.state_of_charge,\n    v.estimated_voltage,\n    (sub.power_level * 1000) / v.estimated_voltage AS estimated_amps\nFROM (\n    SELECT state_of_charge, power_level\n    FROM $Event\n    WHERE session = $Session\n    AND power_level = (\n        SELECT MAX(power_level)\n        FROM $Event\n        WHERE session = $Session\n    )\n) AS sub,\nLATERAL (\n    SELECT \n        CASE\n            WHEN sub.state_of_charge >= 100 THEN 403\n            WHEN sub.state_of_charge >= 95 THEN 401\n            WHEN sub.state_of_charge >= 90 THEN 399\n            WHEN sub.state_of_charge >= 85 THEN 396\n            WHEN sub.state_of_charge >= 80 THEN 393\n            WHEN sub.state_of_charge >= 75 THEN 390\n            WHEN sub.state_of_charge >= 70 THEN 387\n            WHEN sub.state_of_charge >= 65 THEN 384\n            WHEN sub.state_of_charge >= 60 THEN 381\n            WHEN sub.state_of_charge >= 55 THEN 378\n            WHEN sub.state_of_charge >= 50 THEN 375\n            WHEN sub.state_of_charge >= 45 THEN 372\n            WHEN sub.state_of_charge >= 40 THEN 369\n            WHEN sub.state_of_charge >= 35 THEN 366\n            WHEN sub.state_of_charge >= 30 THEN 363\n            WHEN sub.state_of_charge >= 25 THEN 360\n            WHEN sub.state_of_charge >= 20 THEN 357\n            WHEN sub.state_of_charge >= 15 THEN 354\n            WHEN sub.state_of_charge >= 10 THEN 351\n            WHEN sub.state_of_charge >= 5 THEN 348\n            WHEN sub.state_of_charge >= 0 THEN 343\n        END AS estimated_voltage\n) v;"
    }
   ]
  },
  {
   "title": "Track Map",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,latitude AS \"lat1\",longitude AS \"lon1\",speed\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '1';"
    },
    {
     "rawSql": "SELECT\n  time,latitude AS \"lat2\",longitude AS \"lon2\",speed\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '2';"
    },
    {
     "rawSql": "SELECT\n  time,latitude AS \"lat3\",longitude AS \"lon3\",speed\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '3';"
    },
    {
     "rawSql": "SELECT\n  time,latitude AS \"lat4\",longitude AS \"lon4\",speed\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '4';"
    }
   ]
  },
  {
   "title": "Fastest Lap Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(to_timestamp(MAX(elapsed_time) / 1000.0), 'MI:SS.MS') AS \"Lap Time\"\nFROM \n  $Event \nWHERE \n  session = $Session \nGROUP BY \n  lap \nORDER BY \n  \"Lap Time\" \nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Max Inverter Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nGREATEST(\n  MAX(front_inverter_temp * 100),\n  MAX(rear_inverter_temp * 100)\n) AS max_inverter_temp\nFROM\n  $Event\nWHERE\n  session = $Session;"
    }
   ]
  },
  {
   "title": "Max Battery Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  GREATEST(\n    MAX(battery_temp * 100)) AS max_battery_temp\nFROM\n  $Event\nWHERE\n  session = $Session;"
    }
   ]
  },
  {
   "title": "Max Brake Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT GREATEST(\n  MAX(brake_temperature_front_left * 100),\n  MAX(brake_temperature_front_right * 100),\n  MAX(brake_temperature_rear_left * 100),\n  MAX(brake_temperature_rear_right * 100)) AS max_brake_temp\nFROM\n  $Event\nWHERE\n  session = $Session;"
    }
   ]
  },
  {
   "title": "Max Tire Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT GREATEST(\n  MAX(tire_pressure_front_left * 14.5038),\n  MAX(tire_pressure_front_right * 14.5038),\n  MAX(tire_pressure_rear_left * 14.5038),\n  MAX(tire_pressure_rear_right * 14.5038)) AS max_tire_pressure\nFROM\n  $Event \nWHERE\n  session = $Session;"
    }
   ]
  },
  {
   "title": "Lap Speed Comparison",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,speed AS \"Lap 1\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '1'"
    },
    {
     "rawSql": "SELECT\n  time,speed AS \"Lap 2\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '2'"
    },
    {
     "rawSql": "SELECT\n  time,speed AS \"Lap 3\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '3'"
    },
    {
     "rawSql": "SELECT\n  time,speed AS \"Lap 4\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = '4'"
    }
   ]
  },
  { "title": "Lap Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Lap Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  to_char(to_timestamp(MAX(elapsed_time) / 1000.0), 'MI:SS.MS') AS fastest_lap_time \nFROM\n  $Event \nWHERE\n  session = $Session AND lap = $Lap\nGROUP BY\n  lap \nORDER BY\n  fastest_lap_time \nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Top Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(speed) AS top_speed\nFROM\n  $Event\nWHERE\n  lap = $Lap AND session = $Session;"
    }
   ]
  },
  {
   "title": "Max Power",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(power_level) AS max_power_level\nFROM\n  $Event\nWHERE\n  lap = $Lap AND session = $Session;"
    }
   ]
  },
  {
   "title": "Max Amps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "A" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    sub.state_of_charge,\n    v.estimated_voltage,\n    (sub.power_level * 1000) / v.estimated_voltage AS estimated_amps\nFROM (\n    SELECT state_of_charge, power_level\n    FROM $Event\n    WHERE session = $Session AND lap = $Lap\n    AND power_level = (\n        SELECT MAX(power_level)\n        FROM $Event\n        WHERE session = $Session AND lap = $Lap\n    )\n) AS sub,\nLATERAL (\n    SELECT \n        CASE \n          WHEN sub.state_of_charge >= 100 THEN 403\n          WHEN sub.state_of_charge >= 95 THEN 401\n          WHEN sub.state_of_charge >= 90 THEN 399\n          WHEN sub.state_of_charge >= 85 THEN 396\n          WHEN sub.state_of_charge >= 80 THEN 393\n          WHEN sub.state_of_charge >= 75 THEN 390\n          WHEN sub.state_of_charge >= 70 THEN 387\n          WHEN sub.state_of_charge >= 65 THEN 384\n          WHEN sub.state_of_charge >= 60 THEN 381\n          WHEN sub.state_of_charge >= 55 THEN 378\n          WHEN sub.state_of_charge >= 50 THEN 375\n          WHEN sub.state_of_charge >= 45 THEN 372\n          WHEN sub.state_of_charge >= 40 THEN 369\n          WHEN sub.state_of_charge >= 35 THEN 366\n          WHEN sub.state_of_charge >= 30 THEN 363\n          WHEN sub.state_of_charge >= 25 THEN 360\n          WHEN sub.state_of_charge >= 20 THEN 357\n          WHEN sub.state_of_charge >= 15 THEN 354\n          WHEN sub.state_of_charge >= 10 THEN 351\n          WHEN sub.state_of_charge >= 5 THEN 348\n          WHEN sub.state_of_charge >= 0 THEN 343\n        END AS estimated_voltage\n) v;"
    }
   ]
  },
  {
   "title": "Track Map",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,latitude AS \"lat\",longitude AS \"lon\",speed\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Max Inverter Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT GREATEST(\n  MAX(front_inverter_temp * 100),\n  MAX(rear_inverter_temp * 100)) AS max_inverter_temp\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Max Battery Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT GREATEST(\n  MAX(battery_temp * 100)) AS max_battery_temp\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Max Brake Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT GREATEST(\n  MAX(brake_temperature_front_left * 100),\n  MAX(brake_temperature_front_right * 100),\n  MAX(brake_temperature_rear_left * 100),\n  MAX(brake_temperature_rear_right * 100)) AS max_brake_temp\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Max Tire Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "pressurepsi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT GREATEST(\n  MAX(tire_pressure_front_left * 14.5038),\n  MAX(tire_pressure_front_right * 14.5038),\n  MAX(tire_pressure_rear_left * 14.5038),\n  MAX(tire_pressure_rear_right * 14.5038)) AS max_tire_pressure\nFROM\n  $Event \nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Brake Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  brake_temperature_front_left * 100 AS \"Front Left Brake Temp (%)\",\n  brake_temperature_front_right * 100 AS \"Front Right Brake Temp (%)\",\n  brake_temperature_rear_left * 100 AS \"Rear Left Brake Temp (%)\",\n  brake_temperature_rear_right * 100 AS \"Rear Right Brake Temp (%)\"\nFROM\n  $Event \nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Drivetrain Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  battery_temp * 100 AS \"Battery Temp (%)\",\n  front_inverter_temp * 100 AS \"Front Inverter Temp (%)\",\n  rear_inverter_temp * 100 AS \"Rear Inverter Temp (%)\"\nFROM\n  $Event \nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Brake Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  brake_pressure * 14.5038 AS \"Brake Pressure (PSI)\"\nFROM\n  $Event \nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Tire Pressures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  tire_pressure_front_left * 14.5038 AS \"Front Left Tire Pressure (PSI)\",\n  tire_pressure_front_right * 14.5038 AS \"Front Right Tire Pressure (PSI)\",\n  tire_pressure_rear_left * 14.5038 AS \"Rear Left Tire Pressure (PSI)\",\n  tire_pressure_rear_right * 14.5038 AS \"Rear Right Tire Pressure (PSI)\"\nFROM\n  $Event \nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Throttle Position",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,throttle_position AS \"Throttle Position (%)\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Tire Slip",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  tire_slip_front_left * 100 AS \"Front Left Tire Slip (%)\",\n  tire_slip_front_right * 100 AS \"Front Right Tire Slip (%)\",\n  tire_slip_rear_left * 100 AS \"Rear Left Tire Slip (%)\",\n  tire_slip_rear_right * 100 AS \"Rear Right Tire Slip (%)\"\nFROM\n  $Event \nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Yaw Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "rotrads" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,yaw_rate * 100 AS \"Yaw Rate (rad/s)\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Steering Angle / Steering Angle Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,steering_angle AS \"Steering Angle (°)\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    },
    {
     "rawSql": "SELECT\n  time,steering_angle_rate AS \"Steering Angle (°/s)\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,state_of_charge AS \"SoC (%)\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Power Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,power_level AS \"Power Level (kW)\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE \n    WHEN state_of_charge >= 100 THEN 403\n    WHEN state_of_charge >= 95 THEN 401\n    WHEN state_of_charge >= 90 THEN 399\n    WHEN state_of_charge >= 85 THEN 396\n    WHEN state_of_charge >= 80 THEN 393\n    WHEN state_of_charge >= 75 THEN 390\n    WHEN state_of_charge >= 70 THEN 387\n    WHEN state_of_charge >= 65 THEN 384\n    WHEN state_of_charge >= 60 THEN 381\n    WHEN state_of_charge >= 55 THEN 378\n    WHEN state_of_charge >= 50 THEN 375\n    WHEN state_of_charge >= 45 THEN 372\n    WHEN state_of_charge >= 40 THEN 369\n    WHEN state_of_charge >= 35 THEN 366\n    WHEN state_of_charge >= 30 THEN 363\n    WHEN state_of_charge >= 25 THEN 360\n    WHEN state_of_charge >= 20 THEN 357\n    WHEN state_of_charge >= 15 THEN 354\n    WHEN state_of_charge >= 10 THEN 351\n    WHEN state_of_charge >= 5 THEN 348\n    WHEN state_of_charge >= 0 THEN 343\n  END AS \"Voltage (V)\",time\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,speed AS \"Speed (MPH)\"\nFROM\n  $Event\nWHERE\n  session = $Session AND lap = $Lap;"
    }
   ]
  }
 ]
}